name: Manage New Issues

on:
  issues:
    types:
      - opened

jobs:
  manage_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Grants permission to modify issues
    steps:
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add a comment to the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "Thank you for submitting this issue! Our team will review it shortly."

      - name: Add labels to the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "Approval Pending" --add-label "bug"

      - name: Assign issue to milestone "Implemented"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          MILESTONE_NUMBER=$(gh api repos/$REPO/milestones --jq '.[] | select(.title=="Implemented") | .number')
          if [ -n "$MILESTONE_NUMBER" ]; then
            gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --milestone "$MILESTONE_NUMBER"
          else
            echo "Milestone 'Implemented' not found."
          fi
