name: Issue Commenter

on:
  issues:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the issue
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          This is new comment for work flow testing on issue creation
