name: Manage New Issues

on:
  issues:
    types:
      - opened

jobs:
  manage_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Grants permission to modify issues
    steps:
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add the "ask for approval" label to the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "ask for approval"

      - name: Add a comment to the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "New issue from ServiceNow is created"

      - name: Add the "bug" label to the issue
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: |
          gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "bug"
