name: Issue Approval Workflow

on:
  issue_comment:
    types: [created]

jobs:
  approval-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check comment for approval
        uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            const issueNumber = context.payload.issue.number;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            if (comment.includes("approve")) {
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: ["Approved"]
              });
            } else if (comment.includes("reject")) {
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: ["Rejected"]
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
